### ISSUE TITLE
X-ABShowAs converting to X-ABSHOWAS which breaks in MAC contact app

### ISSUE THREAD

**Issue by ningappa** [nextcloud/3rdparty#201]
https://github.com/nextcloud/3rdparty/blob/2146ef45734f855676965b65990d509192666264/sabre/vobject/lib/Document.php#L201

Possible solution.

```
            if (strpos(strtoupper($name), "X-") === 0) {
                $name = substr($name, $i + 1);
            } else {
                $name = strtoupper(substr($name, $i + 1));
            }
```

**Comment by MorrisJobke** [comment]
cc @skjnldsv @georgehrke

**Comment by georgehrke** [comment]
We (or actually Sabre/VObject) are just following the recommendation in the standard here:

```
   Property names and parameter names are case-insensitive (e.g., the
   property name "fn" is the same as "FN" and "Fn").  Parameter values
   MAY be case-sensitive or case-insensitive, depending on their
   definition.  Parameter values that are not explicitly defined as
   being case-sensitive are case-insensitive.  Based on experience with
   vCard 3 interoperability, it is RECOMMENDED that property and
   parameter names be upper-case on output.
```
https://tools.ietf.org/html/rfc6350#page-8

If the macOS/iOS address book can't deal with uppercase property names, this is definitely a bug in iOS/macOS. Please open a bug report there. -> https://bugreport.apple.com/

Feel also free to open a ticket in https://github.com/sabre-io/vobject/issues, the bug tracker of the upstream software used here. But since it's just following the standard's recommendation, I don't think they will change the behaviour. (If you open a ticket, please link it here for reference, thx!)
